server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project_maldo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_general_ci&useBulkStmts=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
   
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    properties:
      org.hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.revision_on_collection_change: true
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false
         
  liquibase:
    enabled: true
    change-log: classpath://db/changelog/changelog-master.xml

  server:
    tomcat:
      relaxed-query-chars: [ '{','}','[',']','$','=', '?' ]
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB


  profiles:
    active:
    - spring



